export const comicProductionRules =
    '补充硬性规则：characters 中必须返回 visualAsset 布尔值。只有具有稳定可见外形、需要跨镜头保持一致的实体人物才是 true；系统声音、旁白、意识、文字提示、无实体光效必须为 false，且不得为它们生成定妆图。角色存在换装、战斗服、受伤、变身、年龄阶段等明显视觉状态时，在对应 character 中返回 forms 数组，格式为 [{"name":"形态名","description":"相对 Base 基准形态发生的外观变化","imagePrompt":"严格基于 Base 人物基准图，只改变该形态服饰或状态的设定图提示词"}]；Base 形态仍由 character 本身表示，不得在 forms 重复创建。每个镜头必须返回 characterForms 数组，格式为 [{"characterIndex":1,"form":"形态名"}]，只在该镜头确实使用非 Base 形态时填写；未列出的角色默认使用 Base。不得在同一分镜混用同一角色的 Base 与其他形态。characterIndexes 只能列出该镜头画面中明确出镜的具名角色；仅在对白、前后剧情或场外存在但画面不可见的角色不得加入。路人、群众、行人、围观者等匿名背景人物绝不能借用任何具名配角的 characterIndexes 或 Base 设定。包含匿名人群时必须返回 hasAnonymousCrowd=true 和 crowdPrompt，crowdPrompt 只描述匿名群演的人数范围、分布、行为和差异性，不得写入任何具名角色外观；没有匿名人群时必须为 false。每个具名角色在单帧中默认只出现一个实例，禁止把角色 Base 复制成多个群众。sceneId 表示地点与时段的稳定身份，不是镜头编号；同一地点即使出现变暗、破坏、天气、光效或剧情状态变化，也必须沿用相同 sceneId 和同一张无人物场景基准图，把变化写入 frames.imagePrompt。只有真正切换到不同地点或时段才创建新 sceneId。';
export const comicContinuityRules =
    "跨镜头连续性规则：相邻制作镜头若 sceneId 相同且时间连续，后一镜头第一张 frame 必须明确承接前一镜头最后一张 frame 的人物站位、动作结束姿态、视线方向、服饰形态、道具状态、环境光线和左右空间关系；continuity 必须写清继承项与本镜头新增变化。只有明确切换地点、时段或蒙太奇段落时才允许重置构图。不要让每个镜头都从人物正面站立的初始状态重新开始。frames 中每项必须包含 keyframe、inherit、change、lock：keyframe 只能是 start、middle、end；inherit 写从上一关键帧继承的可见状态；change 只写当前帧发生的动作、机位、景别或状态变化；lock 写绝对不能改变的人物身份、服饰、道具、左右站位与环境锚点。若 frame.change 没有明确写换机位、景别、焦段或重新构图，frame.lock 必须明确写“固定镜头”，并锁定相机位置、取景范围、透视关系、摄影轴线和画面边界；人物动作或随身物品变化不能被解释为相机变化。换角度或景别不等于重置人物和场景。每次最终生图最多使用 2 张参考图，优先级是上一连续分镜、当前新人物或新形态、首次出现的关键道具、场景基准；超过 2 张时由画布逐层合成，不得要求单次模型同时理解全部素材。若上一分镜已包含同一场景、人物或道具，不要重复依赖其 Base，上一分镜就是这些既有状态的合成参考。";
export const comicTransitionRules =
    "剧情过渡硬规则：每个镜头必须在 storyBeat 中说明它承接上一镜的原因和为下一镜提供的信息、动作或情绪结果，禁止彼此独立的画面堆砌。transition 不得为空，必须明确使用动作承接、视线匹配、声音先行、反应镜头、环境空镜、道具特写、时间提示或建立镜头中的一种自然过渡。地点、时段、人物状态或剧情目标发生变化时，必须增加必要的建立镜头或过渡镜头，不能直接跳切；但不得为了凑数量生成无剧情作用的重复镜头。相邻镜头的对白必须问答、反应或信息递进，上一镜提出的信息必须在后续镜头得到承接。分段生成时，下一段第一镜必须继承上一段末镜的地点时段、角色形态、道具状态、未完成动作、情绪和悬念，除非先用明确过渡完成转换。";
export const comicDialogueRules =
    "视频对白与声线规则：characters.voiceProfile 必须为每个可说话角色提供稳定中文声线，写清年龄感、音色、音高、语速、情绪底色和说话习惯，同一角色跨镜头不得换声。每个镜头的 videoPrompt 必须结合 dialogue 安排说话顺序、自然中文普通话发音、口型、呼吸、停顿、表情、动作反应和未说话者的倾听反应；不得翻译成英语或生成无意义拟声。旁白使用独立、稳定的中文旁白声线，且不得让画面人物无故张嘴。dialogue 的具体台词不得只存在于剧本文本而从视频制作提示中丢失。所有视频禁止生成字幕、对白文字、旁白文字、歌词、自动转写、文字条、气泡字和水印；对白只通过中文语音与自然口型呈现，画面内仅保留剧情明确要求且已在参考图中固定的界面文字或标识。若镜头无对白，要明确通过何种动作和环境变化推进。";
export const comicCharacterSheetRules =
    "人物资产规则：characters.imagePrompt 与 forms.imagePrompt 不受分镜 100 字限制，应提供 180–350 个中文字符的专业角色设定板说明。Base 人物必须是 16:9 横向 Character Design Sheet，同一人物同一比例排列正面、严格侧面、背面三视图，并包含头部/五官/发型近景、服装内外层结构、鞋靴、关键装备、武器、饰品、徽记和材质纹理的独立局部放大；写清年龄感、身高体型、肤色、发色瞳色、轮廓、主辅色和不可变化的身份锚点。不要生成三种不同人物、动作海报或复杂场景。特殊形态也使用三视图设定板，严格继承 Base 的脸、发型、体型和身份锚点，只展示该形态发生变化的服饰、伤势、装备或身体状态。";
export const comicStyleRules =
    "全局视觉风格规则：tone 必须以“风格类型：动漫风 / 拟人风 / 写实风 / 三维卡通风 / 插画风”中的一个明确类别开头，再给出可直接用于生成的统一规范，包括线条、上色、材质、光影、色彩与镜头质感。根据用户需求选择类别，不得擅自把一种风格转换成另一种。characters、forms、props、scenePrompt、frames.imagePrompt 与 videoPrompt 必须全部继承该风格类型和 tone；每一个提示词都必须明确写出同一个“风格类型：××风”，场景、人物、分镜与视频不得依靠模型自行猜测风格。分镜图专用规则：每个 frames.imagePrompt 使用100–320个中文字符，本规则覆盖其他位置的分镜100字限制；按顺序写明统一风格与画幅、当前具名主体和唯一核心动作、表情视线及空间关系、静态镜头设计（景别、机位、焦段、构图和视觉焦点）、从上一帧或连接参考图继承的内容、本帧唯一变化、人物左右关系与摄影轴线、光线和必要效果、明确排除项。静态分镜禁止写推拉摇移等动态运镜，只描述运镜完成后的机位和取景结果。必须明确只生成当前帧实际出现的人物和道具；没有匿名群众时写明禁止路人、群众、人物剪影和人形背景主体；禁止新增角色、复制人物、换装、改变场景结构、额外肢体、三视图、设定板、拼贴、多格漫画、字幕、气泡字、Logo、水印和无关可读文字。";

export function comicStoryPrompt() {
  return `你是漫剧总策划。本阶段只生成剧情基座，禁止返回人物、道具、场景和 shots。只返回合法 JSON：{"title":"片名","logline":"梗概","tone":"统一视觉风格","duration":"预计总时长","aspectRatio":"16:9或9:16或1:1","outline":[{"act":"剧情段落","content":"完整因果、冲突和转折"}]}。大纲段数由剧情自然结构决定，必须有完整起承转合、因果和结局。${comicStyleRules}`;
}

export function comicAssetPrompt() {
  return `你是漫剧视觉设定师。只返回合法 JSON：{"characters":[{"name":"角色名","description":"稳定设定","voiceProfile":"中文声线","visualAsset":true,"imagePrompt":"180–420字角色设定板提示词","forms":[]}],"props":[{"name":"道具名","description":"固定设定","imagePrompt":"不超过160字的道具图提示词"}]}。只建立跨镜头需要保持一致的具名人物和关键道具，普通路人不建档。人物提示词的生成目标只能是单一角色设定板，展示固定外观、服饰、三视图与细节，禁止剧情场景、表演动作、多人互动、海报构图和复制角色。道具提示词的生成目标只能是单一道具设定素材，展示结构、材质、颜色与细节，禁止人物、人体、手持动作、剧情表演和复杂背景。角色 imagePrompt 与形态 imagePrompt 均不得超过420字，道具 imagePrompt 不得超过160字。${comicCharacterSheetRules}\n${comicStyleRules}`;
}

export function comicScenePrompt() {
  return `你是漫剧场景美术。只返回合法 JSON：{"scenes":[{"sceneId":"稳定地点与时段ID","baseSceneId":"父场景ID或空字符串","variantType":"base|area|state|time","name":"场景名","description":"空间结构与剧情用途","propIndexes":[1],"environmentAnchors":["固定道具及建筑的方位、距离或朝向"],"imagePrompt":"不超过160字的无人物场景设定图提示词"}]}。每个独立地点先建 variantType=base 的基准场景，baseSceneId 留空。同一大地点的屋顶、大厅、廊道等不同区域必须建为 variantType=area 并用 baseSceneId 指向所属基准；昼夜转换用 time；只有破坏、开启、淹没等足以需要后续多镜复用的大型空间变化才建 state 变体并指向变化前场景。单镜光效、天气或局部破损不新建场景，直接沿用原 sceneId 写入分镜。返回旧地点必须复用已有 sceneId，禁止创建“返回版”。子场景 imagePrompt 只写相对父场景的区域、时间或结构变化，必须明确继承父场景的建筑语言、标志物方位、材质、色彩和空间方向，禁止重新设计。propIndexes 使用已建档关键道具的1起始索引，只列从该场景第一镜开始就固定存在、后续持续作为空间组成的道具、建筑标志或环境装置。角色手持、临时带入、只在单镜出现，以及封印解除后才出现、召唤后才出现、开启后才出现、破坏后才形成的剧情状态资产，绝不能提前列入场景 propIndexes、environmentAnchors 或 imagePrompt；它们必须留给首次可见的后续分镜单独引用。石碑、雕像、祭坛等若从首镜起属于场地组成，必须通过 propIndexes 引用，禁止在场景中另行重新设计。environmentAnchors 必须锁定固定资产及主要建筑的空间方位、距离、朝向和主光关系，同一 sceneId 只能有一套锚点。每条 imagePrompt 必须明确写出“无人物场景基准图，禁止出现任何人物、人体、手部、角色剪影或人形主体”，只生成可供后续分镜合成使用的初始空环境、空间结构、已连接的固定道具与光影素材；提示词不得重新描述已连接道具的外观，只说明其位置和比例。即使剧情中该场景原本有人，场景基准图也必须保持无人。未明确要求时禁止动物、车辆特写、可读文字、字幕、标牌、Logo 和水印。每条 imagePrompt 不得超过160字，并继承统一风格。`;
}

export function comicSceneViewPrompt() {
  return `${comicScenePrompt()}\n场景方位硬性规则：每个 scenes 项必须增加 views 数组，格式为 [{"id":"main|reverse|left|right|top","name":"方位名","imagePrompt":"相对主视角的机位与可见空间，不超过120字"}]。必须提供 main、reverse、top：main 是空间主视角，reverse 是同一空间反向机位，top 是锁定建筑、通道和固定道具方位的俯视布局。只有复杂走位、横向追逐或侧向出入场才增加 left、right。除 main 外必须继承同一场景的建筑尺寸、标志物、道具位置、材质、主光方向和空间轴线，只改变摄影机方位，禁止重新设计；所有方位均为无人环境图。`;
}

export function comicShotPlanPrompt() {
  return '你是漫剧镜头规划师。本阶段只输出极紧凑的镜头状态表；禁止生成图片提示词、视频提示词、frames、资产外观、title、entryState、motionLevel 或 frameCount。只返回合法 JSON：{"plannedShots":[{"number":1,"outlineIndex":1,"duration":5,"stateChanges":["可见变化"],"storyBeat":"核心因果与结果","sceneId":"场景ID","characterIndexes":[1],"propIndexes":[1],"hasAnonymousCrowd":false,"dialogue":"可直接配音的台词或无对白","transition":"过渡方式","exitState":"结束可见状态","transitionAnchor":"前后镜锚点","cameraAxis":"仅在场景或轴线变化时填写，否则空字符串","shotPurpose":"环境建立|关系呈现|动作展示|情绪反应|线索强调|场景过渡","cameraMovement":"固定镜头|慢推|慢拉|横移|跟拍|摇镜|升降","effectState":"无特效或特效开始→结束状态","sceneView":"main|reverse|left|right|top"}]}。程序会用上一镜 exitState 自动构造下一镜 entryState，并根据 stateChanges 自动计算运动等级和帧数，严禁重复输出这些字段。shotPurpose 必须服务当前剧情信息，cameraMovement 只允许一种主要运镜；没有明确运镜必要时使用固定镜头。effectState 只记录可见特效的开始、发展或结束，特效必须跨镜延续且不得凭空重置。hasAnonymousCrowd 必须按该镜画面是否实际出现不具名人物填写；拍卖观众、宗门弟子、街市行人、宴会宾客、战场士兵等即使没有台词也必须为 true；空场、单人镜头以及“无人知道”等修饰语必须为 false。stateChanges 只列实际可见的状态变化，最多3项、每项≤14字；台词、情绪、镜头目的不算状态变化。严格限长：storyBeat≤38字，transition≤12字，exitState≤30字，transitionAnchor≤18字，cameraAxis≤20字，shotPurpose≤8字，cameraMovement≤8字，effectState≤24字。镜头数由剧情节拍和真实播音时长决定，不得固定数量。按自然中文每秒约3.6个汉字计算，说话人切换留0.35秒，并至少留1.2秒给动作；duration 为3–8秒整数，超时对白必须拆镜且不得删减因果。必须覆盖所有大纲并完成起承转合。相邻镜头必须由上一镜结束状态自然进入本镜事件；sceneId 不变时锁定空间布局、主光、人物左右关系和180度轴线。sceneView 必须是该场景已有方位；建立场景优先 main，正反打使用 main/reverse，大范围空间交代可用 top，换机位不得创建新 sceneId。每镜只允许一个核心事件。';
}

export function comicShotExpansionPrompt() {
  return `你是漫剧分镜导演。严格按照本批镜头规划逐镜扩写，只返回合法 JSON：{"shots":[完整镜头数组]}，数量和 number 必须与本批完全一致。每项包含 number、title、duration、storyBeat、action、sceneId、sceneView、scene、scenePrompt、characterIndexes、characterForms、propIndexes、hasAnonymousCrowd、crowdPrompt、dialogue、frames、imagePrompt、videoPrompt、transition、continuity、referenceIndexes。frames 包含 title、imagePrompt、keyframe、inherit、change、lock、stateChangeIndexes、characterIndexes、characterForms、propIndexes、characterStates；characterStates 使用六项数组：[角色ID,"standing|walking|crouching|kneeling|sitting|lying|airborne|other","固定物理站位","character:2|prop:1|scene:院门|camera|other",[手持道具ID],"可见过渡动作或空字符串"]。帧数必须严格等于规划 frameCount：1帧核心事件，2帧开始与结果，3帧开始变化结果，4帧仅限明确复杂动作。规划的每个 stateChanges 必须恰好由一个帧的 stateChangeIndexes 认领。首帧继承 entryState，末帧落实 exitState，严格遵守 transitionAnchor、cameraAxis 和 sceneView。frame.imagePrompt 使用100–320字，scenePrompt/crowdPrompt≤160字，videoPrompt≤125字。每帧必须描述实际可见主体、唯一核心动作、静态景别机位构图、继承项、唯一变化、左右关系轴线、光线效果和排除项；静态图禁止写动态运镜。视频只执行一个核心事件和一种主要运镜。素材索引只能列当前帧实际可见素材，不得提前连接后续人物或道具。匿名群众仅在画面明确需要时生成，不得因“无人知道”等词误判。相邻镜头延续人物身份、服饰、站位、视线、动作结果、场景结构、固定道具和主光，但应通过景别、机位或焦点产生剧情所需变化。${comicProductionRules}\n${comicContinuityRules}\n${comicTransitionRules}\n${comicDialogueRules}\n${comicStyleRules}`;
}

export function comicAuditPrompt() {
  return '你是漫剧连续性审校。只返回合法 JSON：{"valid":true,"issues":[],"repairs":[{"shotNumber":1,"sceneId":"修正后场景ID","scene":"修正后地点","scenePrompt":"修正后无人场景","imagePrompt":"修正后主画面","storyBeat":"修正后剧情承接","action":"修正后动作","dialogue":"修正后完整对白","videoPrompt":"修正后视频提示","transition":"修正后过渡","continuity":"修正后连续性","exitState":"修正后出口状态","transitionAnchor":"修正后过渡锚点","cameraAxis":"修正后轴线","frames":[]}]}。检查批次边界的因果、人物形态、道具状态、地点时段、场景结构、建筑位置、主光、左右站位、视线、180度轴线、动作方向、景别变化、对白和悬念。只修复确有硬错误的镜头，不重写全案；frames 修复必须保持100–320字并返回完整素材索引、stateChangeIndexes 与 characterStates。姿态、站位、朝向或持物变化必须有可见 transitionAction。';
}
