import { test, expect, type Page } from '@playwright/test'

async function fixture(page: Page, admin = true, withNode = false) {
  let revision = 1
  const providers = [{ id: 'p', name: '测试服务商', baseUrl: 'https://example.com', proxyUrl: '', enabled: true, hasKey: true, readOnly: false, keyCount: 2, keys: [{ id: 'key-one-id', status: 'ready', cooldownUntil: null as string | null, reason: '' }, { id: 'key-two-id', status: 'cooling', cooldownUntil: '2026-09-20T20:00:00Z', reason: 'rate-limit' }] }]
  const models = [{ id: 'global:m', name: '全局图片模型', model: 'image-test', providerId: 'p', adapter: 'openai-image', kind: 'image', enabled: true, order: 0, creditCost: 0, capabilities: { referenceImages: 1, transparent: true, sizes: ['512x512', '1024x1024'], resolutions: [], aspectRatios: [], minSeconds: 1, maxSeconds: 18 } }]
  const defaults: Record<string, string> = { image: 'global:m' }
  let devices = Array.from({ length: 9 }, (_, i) => ({ id: `device-${i}`, name: i === 0 ? '当前浏览器' : `设备 ${i}`, current: i === 0, lastUsedAt: new Date(Date.now() - i * 60000).toISOString() }))
  const state = () => ({ revision, imported: true, providers, models, defaults })
  await page.route('**/api/**', async route => {
    const req = route.request(), path = new URL(req.url()).pathname
    let body: unknown = {}; let status = 200
    if (path === '/api/users/me') body = { id: 'u', name: '测试管理员', username: 'test', email: 'test@example.invalid', credits: 10, isAdmin: admin }
    else if (path === '/api/auth/devices') body = devices
    else if (path === '/api/auth/devices/revoke-others') { devices = devices.filter(d => d.current); body = { ok: true } }
    else if (path.startsWith('/api/auth/devices/') && req.method() === 'DELETE') { devices = devices.filter(d => d.id !== path.split('/').at(-1)); body = { ok: true } }
    else if (path === '/api/projects') body = [{ id: 'p1', name: '测试画布' }]
    else if (path === '/api/projects/p1/canvas') body = { nodes: withNode ? [{ id: 1, publicId: 'image-test-1', accent: '#8ee7ff', kind: 'image', x: -100, y: -90, width: 240, height: 180, title: '测试图片', body: '生成图片', model: 'global:m', imageSettings: { size: '512x512' }, status: 'idle', progress: 0 }] : [], links: [], camera: { x: 0, y: 0, zoom: 1 }, version: 1 }
    else if (path.includes('id-block')) body = { projectId: 'p1', start: 2, end: 10000 }
    else if (path === '/api/models/catalog') body = { revision, models, defaults }
    else if (path === '/api/admin/models' && req.method() === 'GET') body = state()
    else if (path === '/api/admin/model-providers' && req.method() === 'POST') {
      const data = req.postDataJSON()
      providers.push({ ...data, apiKey: undefined, apiKeys: undefined, hasKey: !!data.apiKeys?.length, keyCount: data.apiKeys?.length || 0, keys: (data.apiKeys || []).map((_: string, i: number) => ({ id: `new-${i}`, status: 'ready', cooldownUntil: null })), readOnly: false, id: 'p2' }); revision++; body = state()
    } else if (path === '/api/admin/model-providers/p' && req.method() === 'PUT') {
      const data = req.postDataJSON(), keys = providers[0].keys.filter(k => data.retainedKeyIds.includes(k.id)).concat(data.apiKeys.map((_: string, i: number) => ({ id: `added-${i}`, status: 'ready', cooldownUntil: null, reason: '' })))
      providers[0] = { ...providers[0], name: data.name, keys, keyCount: keys.length }; revision++; body = state()
    } else if (path === '/api/admin/models' && req.method() === 'POST') {
      const data = req.postDataJSON(); models.push({ ...data, kind: 'image', id: 'global:added' }); revision++; body = state()
    } else if (path === '/api/admin/models/global%3Am' && req.method() === 'PUT') {
      Object.assign(models[0], req.postDataJSON()); revision++; body = state()
    } else if (path.endsWith('/discover')) body = { models: ['new-image-id', 'second-image-id'] }
    else if (path === '/api/admin/model-defaults') { Object.assign(defaults, req.postDataJSON().defaults); revision++; body = state() }
    else if (path.includes('notifications') || path.includes('assets') || path === '/api/user-api-models') body = []
    else if (path === '/api/generation/capabilities') body = { image: { defaultModel: 'global:m' } }
    await route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(body) })
  })
  await page.goto('/#/canvas')
  await expect(page.locator('body')).not.toHaveClass(/app-loading/)
}

test('provider models collapse preserves drafts and restores after search', async ({ page }) => {
  await fixture(page)
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const group = page.locator('[data-provider="p"]')
  const toggle = group.locator('[data-toggle-models]')
  await group.locator('[data-edit-model]').click()
  const name = group.locator('[data-inline-model] [name=name]')
  await name.fill('尚未保存的模型名称')
  await toggle.click()
  await expect(group.locator('.model-provider-models')).toBeHidden()
  await expect(group.getByRole('button', { name: '添加模型', exact: true })).toBeVisible()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.press('Enter')
  await expect(name).toHaveValue('尚未保存的模型名称')
  await toggle.click()
  await page.getByRole('searchbox', { name: '搜索服务商或模型' }).fill('image-test')
  await expect(name).toBeVisible()
  await page.getByRole('searchbox', { name: '搜索服务商或模型' }).fill('')
  await expect(name).toBeHidden()
  await toggle.click()
  await expect(name).toHaveValue('尚未保存的模型名称')
})

for (const width of [375, 1024, 1440]) for (const theme of ['light', 'dark']) test(`global model workspace ${width} ${theme}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.addInitScript(theme => localStorage.setItem('flow-theme-preference', theme), theme)
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await fixture(page)
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const workspace = page.getByRole('dialog', { name: '全局模型管理', exact: true })
  await expect(workspace.locator('.model-model-title').getByText('全局图片模型', { exact: true })).toBeVisible()
  expect(await workspace.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await expect(workspace.locator('[data-tab]')).toHaveCount(0)
  await expect(workspace.locator('[data-import]')).toHaveCount(0)
  await workspace.getByRole('button', { name: '＋ 添加服务商', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '服务商配置', exact: true })
  await editor.getByLabel('连接名称', { exact: true }).fill('我的服务商')
  await editor.getByLabel('接口地址', { exact: true }).fill('https://api.example.com/v1')
  await editor.getByLabel('新增 API 密钥', { exact: true }).fill('test-secret')
  await editor.getByRole('button', { name: '显示密钥' }).click()
  await expect(editor.locator('[name=apiKey]')).toHaveAttribute('type', 'text')
  await editor.getByRole('button', { name: '添加 Key' }).click()
  await editor.locator('[name=apiKey]').nth(1).fill('second-test-secret')
  await editor.getByRole('button', { name: '获取上游模型', exact: true }).click()
  await expect(editor.locator('output')).toContainText('已获取 2 个模型')
  await expect(editor.getByLabel('接口地址', { exact: true })).toHaveValue('https://api.example.com/v1')
  expect(await editor.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `/tmp/canvas-provider-${width}-${theme}.png` })
  const saved = page.waitForRequest(req => new URL(req.url()).pathname === '/api/admin/model-providers' && req.method() === 'POST')
  await editor.getByRole('button', { name: '保存服务商' }).click()
  expect((await saved).postDataJSON().apiKeys).toEqual(['test-secret', 'second-test-secret'])
  await expect(editor).not.toBeVisible()
  await expect(workspace.getByText('我的服务商', { exact: true })).toBeVisible()
  await workspace.getByRole('article', { name: '我的服务商', exact: true }).getByRole('button', { name: '添加模型', exact: true }).click()
  const picker = page.getByRole('dialog', { name: '添加模型', exact: true })
  await picker.getByRole('searchbox').fill('new-image')
  await picker.getByRole('button', { name: /new-image-id/ }).click()
  const inline = workspace.locator('[data-inline-model]')
  await expect(inline.locator('[name=providerId]')).toHaveValue('p2')
  await expect(workspace.locator('select[name=providerId]')).toHaveCount(0)
  await inline.getByLabel('显示名称', { exact: true }).fill('新的图片模型')
  await expect(inline.getByLabel('模型 ID', { exact: true })).toHaveValue('new-image-id')
  await inline.getByLabel('优先级', { exact: true }).fill('25')
  await inline.getByLabel('每次生成点数', { exact: true }).fill('3')
  await expect(inline.getByRole('checkbox', { name: '图片生成' })).toBeChecked()
  expect(await inline.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `/tmp/canvas-model-inline-${width}-${theme}.png` })
  const modelSaved = page.waitForRequest(req => req.method() === 'POST' && new URL(req.url()).pathname === '/api/admin/models')
  await inline.getByRole('button', { name: '保存模型' }).click()
  expect((await modelSaved).postDataJSON()).toMatchObject({ order: '25', creditCost: '3', purposes: ['image'] })
  await expect(workspace.getByRole('article', { name: '我的服务商', exact: true })).toContainText('新的图片模型')
  await workspace.getByRole('button', { name: '选择图片生成默认模型' }).click()
  await page.getByRole('dialog', { name: '选择图片生成默认模型', exact: true }).getByRole('button', { name: /新的图片模型/ }).click()
  await workspace.getByRole('button', { name: '保存默认分配' }).click()
  await expect(workspace.locator('output').first()).toContainText('已保存')
  await expect(workspace.locator('[data-defaults] select')).toHaveCount(0)
  await page.screenshot({ path: `/tmp/canvas-models-${width}-${theme}.png` })
  expect(errors).toEqual([])
})

test('existing keys can be retained or removed; adaptive editor fits short landscape screens', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await fixture(page)
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const workspace = page.getByRole('dialog', { name: '全局模型管理', exact: true })
  await expect(workspace.locator('.model-provider-row')).toContainText('1 冷却中')
  await workspace.getByRole('button', { name: '连接配置', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '服务商配置', exact: true })
  await editor.locator('[name=retainedKeyIds]').first().uncheck()
  await editor.locator('[name=apiKey]').fill('replacement-secret')
  const saved = page.waitForRequest(req => req.method() === 'PUT' && req.url().endsWith('/admin/model-providers/p'))
  await editor.getByRole('button', { name: '保存服务商' }).click()
  const data = (await saved).postDataJSON()
  expect(data.retainedKeyIds).toEqual(['key-two-id'])
  expect(data.apiKeys).toEqual(['replacement-secret'])
  await workspace.getByRole('button', { name: '连接配置', exact: true }).click()
  await expect(editor.locator('[name=retainedKeyIds]')).toHaveCount(2)
  await expect(editor.locator('[name=apiKey]')).toHaveValue('')
  expect(await editor.evaluate(el => el.scrollWidth <= el.clientWidth && el.getBoundingClientRect().bottom <= window.innerHeight)).toBe(true)
})

test('saved Key revalidation preserves draft and unchecked choices, and explains verification failures', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 900 })
  await fixture(page)
  let requests = 0
  await page.route('**/api/admin/model-providers/p/verify-key', async route => {
    requests++
    expect(route.request().postDataJSON()).toEqual({ keyId: 'key-two-id' })
    await route.fulfill({ status: requests === 1 ? 200 : 502, contentType: 'application/json', body: JSON.stringify(requests === 1
      ? { key: { id: 'key-two-id', status: 'ready', cooldownUntil: null }, message: '模型列表验证通过，认证冷却已解除' }
      : { error: '验证返回 HTTP 403，原冷却状态未改变' }) })
  })
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  await page.getByRole('button', { name: '连接配置', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '服务商配置', exact: true })
  await editor.locator('[name=retainedKeyIds]').first().uncheck()
  await editor.locator('[name=apiKey]').fill('new-unsaved-secret')
  await editor.getByRole('button', { name: '重新验证 Key 2', exact: true }).click()
  await expect(editor.locator('.model-key-verification').nth(1)).toContainText('认证冷却已解除')
  await expect(editor.locator('[name=apiKey]')).toHaveValue('new-unsaved-secret')
  await expect(editor.locator('[name=retainedKeyIds]').first()).not.toBeChecked()
  await expect(editor.locator('.model-saved-key').nth(1)).toContainText('无冷却')
  await expect(page.locator('.model-provider-meta')).not.toContainText('冷却中')
  await editor.getByRole('button', { name: '重新验证 Key 2', exact: true }).click()
  await expect(editor.locator('.model-key-verification').nth(1)).toContainText('HTTP 403')
  await editor.getByRole('button', { name: '重新验证 Key 1', exact: true }).click()
  await expect(editor.locator('.model-key-verification').first()).toContainText('请先保存')
  await editor.getByLabel('接口地址', { exact: true }).fill('https://changed.example.com')
  await editor.getByRole('button', { name: '重新验证 Key 2', exact: true }).click()
  await expect(editor.locator('.model-key-verification').nth(1)).toContainText('请先保存')
  expect(requests).toBe(2)
  expect(await editor.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: '/tmp/canvas-key-verification-mobile.png' })
})

test('ordinary users do not see admin entry', async ({ page }) => {
  await fixture(page, false)
  await page.locator('#workspace-user').click()
  await expect(page.locator('#open-global-models')).toBeHidden()
  await expect(page.locator('#admin-actions')).toBeHidden()
})

test('search preserves default drafts and model ownership; known Agnes selection fills its contract', async ({ page }) => {
  await fixture(page)
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const workspace = page.getByRole('dialog', { name: '全局模型管理', exact: true })
  await workspace.getByRole('button', { name: '选择图片生成默认模型' }).click()
  await page.getByRole('dialog', { name: '选择图片生成默认模型', exact: true }).getByRole('button', { name: /手动选择/ }).click()
  await workspace.getByRole('searchbox').fill('not-found')
  await expect(workspace.locator('.model-provider-group:visible')).toHaveCount(0)
  await expect(workspace.locator('[data-defaults] [name=image]')).toHaveValue('')
  await workspace.getByRole('searchbox').fill('image-test')
  await expect(workspace.locator('.model-provider-group:visible')).toHaveCount(1)
  await workspace.getByRole('button', { name: '保存默认分配' }).click()
  await expect(workspace.locator('output').first()).toContainText('已保存')
  await workspace.getByRole('button', { name: '手动添加模型' }).click()
  const editor = workspace.locator('[data-inline-model]')
  await editor.getByLabel('模型 ID', { exact: true }).fill('agnes-video-2.5-flash')
  await expect(editor.getByRole('combobox', { name: '接口协议', exact: true })).toHaveValue('agnes-video')
  await expect(editor.locator('[name=referenceImages]')).toHaveValue('5')
  await expect(editor.locator('[name=resolutions]')).toHaveValue('720p')
  await expect(editor.locator('[name=minSeconds]')).toHaveValue('4')
  await expect(editor.locator('[name=maxSeconds]')).toHaveValue('12')
  await expect(editor.locator('[name=providerId]')).toHaveValue('p')
})

test('failed model discovery keeps manual addition available and reports the failure', async ({ page }) => {
  await fixture(page)
  await page.route('**/api/admin/model-providers/p/discover', route => route.fulfill({ status: 502, json: { error: '上游暂不可用，请重试' } }))
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const workspace = page.getByRole('dialog', { name: '全局模型管理', exact: true })
  await workspace.getByRole('button', { name: '添加模型', exact: true }).click()
  await expect(workspace.locator('output')).toContainText('上游暂不可用')
  await workspace.getByRole('button', { name: '手动添加模型' }).click()
  await expect(workspace.locator('[data-inline-model]')).toBeVisible()
})

test('inline configuration retains edits on failure and filtering; default picker supports keyboard', async ({ page }) => {
  await fixture(page)
  await page.locator('#workspace-user').click()
  await page.locator('#admin-actions summary').click()
  await page.locator('#open-global-models').click()
  const workspace = page.getByRole('dialog', { name: '全局模型管理', exact: true })
  await workspace.getByRole('button', { name: '配置 全局图片模型', exact: true }).click()
  const form = workspace.locator('[data-inline-model]')
  await form.getByLabel('优先级', { exact: true }).fill('9')
  await workspace.getByRole('searchbox').fill('does-not-match')
  await expect(form).toBeVisible()
  await expect(form.getByLabel('优先级', { exact: true })).toHaveValue('9')
  await page.route('**/api/admin/models/global%3Am', route => route.fulfill({ status: 409, json: { error: '配置已被其他管理员更新，请刷新后再保存' } }))
  await form.getByRole('button', { name: '保存模型', exact: true }).click()
  await expect(form.locator('output')).toContainText('其他管理员')
  await expect(form.getByLabel('优先级', { exact: true })).toHaveValue('9')
  await form.getByRole('button', { name: '取消', exact: true }).click()
  await page.locator('.model-confirm').getByRole('button', { name: '确认', exact: true }).click()
  const trigger = workspace.getByRole('button', { name: '选择图片生成默认模型' })
  await trigger.click()
  const picker = page.getByRole('dialog', { name: '选择图片生成默认模型', exact: true })
  await picker.getByRole('searchbox').fill('自动')
  await page.keyboard.press('Tab')
  await page.keyboard.press('Enter')
  await expect(picker).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await expect(workspace.locator('[data-defaults] [name=image]')).toHaveValue('@auto')
})

for (const width of [375, 1440]) test(`account device list and admin submenu ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  await fixture(page)
  await page.locator('#workspace-user').click()
  const menu = page.locator('#workspace-user-menu'), rows = menu.locator('[data-trusted-devices] > div')
  await expect(rows).toHaveCount(3)
  await expect(rows.first()).toContainText('当前设备')
  await menu.getByRole('button', { name: '显示更多（还有 6 台）' }).click()
  await expect(rows).toHaveCount(8)
  await menu.getByRole('button', { name: '收起', exact: true }).click()
  await expect(rows).toHaveCount(3)
  await expect(menu.locator('#open-global-models')).toBeHidden()
  await menu.locator('#admin-actions summary').click()
  await expect(menu.locator('#open-global-models')).toBeVisible()
  await expect(menu.locator('#open-credit-admin')).toBeVisible()
  expect(await menu.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: `/tmp/canvas-account-menu-${width}.png` })
  await menu.locator('#open-credit-admin').click()
  await expect(page.locator('#credit-admin-form')).toBeVisible()
  await expect(page.locator('#credit-redeem-form')).toBeHidden()
  await page.locator('#lab-modal [data-lab-close]').first().click()
  await page.locator('#workspace-user').click()
  await expect(menu.locator('#admin-actions')).not.toHaveAttribute('open', '')
  await menu.getByRole('button', { name: '退出 设备 1', exact: true }).click()
  await expect(menu.locator('.device-list-status')).toHaveText('设备已退出')
  await expect(menu.locator('.trusted-device-section > div:first-child small')).toContainText('8')
})

test('image composer uses catalog model and preserves configured custom size on reload', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await fixture(page, false, true)
  await expect(page.locator('#canvas-pixi')).toBeVisible()
  await page.locator('.flow-node .image-empty-state b').click()
  const panel = page.locator('.flow-node.selected > .image-config-panel')
  await expect(panel).toBeVisible()
  await expect(panel.locator('[data-image-model-label]')).toHaveText('全局图片模型')
  await panel.locator('[data-image-settings-label]').click()
  const size = panel.getByRole('combobox', { name: '图片尺寸' })
  await expect(size).toBeVisible()
  await expect(size).toHaveValue('512x512')
  await size.selectOption('1024x1024')
  await expect(panel.locator('[data-image-settings-label]')).toContainText('1:1')
})

test('legacy upstream ID stays selected without duplicating the catalog model', async ({ page }) => {
  await fixture(page, false, true)
  await page.route('**/api/projects/p1/canvas', route => route.fulfill({ json: {
    nodes: [{ id: 1, publicId: 'legacy-image', accent: '#8ee7ff', kind: 'image', x: -100, y: -90, width: 240, height: 180, title: '旧图片', body: '生成图片', model: 'image-test', status: 'idle', progress: 0 }],
    links: [], camera: { x: 0, y: 0, zoom: 1 }, version: 1,
  } }))
  await page.reload()
  await page.locator('.flow-node .image-empty-state b').click()
  const panel = page.locator('.flow-node.selected > .image-config-panel')
  await expect(panel.locator('[data-image-model-label]')).toHaveText('全局图片模型')
  await expect(panel.locator('[data-image-field="model"] option')).toHaveCount(1)
  await expect(panel.locator('[data-image-field="model"]')).toHaveValue('image-test')
  await expect(panel.locator('[data-image-model="image-test"]')).toHaveCount(1)
})
