import type { CatalogModel } from './catalog'
import type { AdminModels, ProviderView } from './admin-api'
export const kinds = { image: '图片', video: '视频', text: '文本' }
export const purposes = { image: '图片生成', video: '视频生成', prompt: '提示词助手', comic: '漫画对话与规划' }
export const adapters: Record<string, string> = { 'openai-image': 'OpenAI 兼容 · 图片', 'openai-video': 'OpenAI 兼容 · 视频', 'agnes-image': 'Agnes · 图片', 'agnes-video': 'Agnes · 视频', 'openai-chat': 'OpenAI 兼容 · Chat Completions' }
export const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
const field = (name: string, title: string, value: unknown = '', options = '') => `<label>${title}<input name="${name}" value="${escape(value)}" ${options}></label>`
export function providerForm(provider?: ProviderView) {
  const reasons: Record<string, string> = { 'rate-limit': '触发限流', quota: '额度不足', authentication: '认证失败' }
  return `${field('name', '连接名称', provider?.name, 'required maxlength="120"')}${field('baseUrl', '接口地址', provider?.baseUrl, 'required type="url" placeholder="https://api.example.com/v1"')}<section class="model-key-section" aria-label="API 密钥池"><h3>API 密钥 <small>最多 32 个</small></h3><p class="model-help">自动轮换可用 Key；限流、额度不足或认证失败时冷却并尝试下一个。</p>${(provider?.keys || []).map((key, index) => `<label class="model-saved-key"><input type="checkbox" name="retainedKeyIds" value="${escape(key.id)}" checked><span>Key ${index + 1}<small>${key.status === 'cooling' ? `${escape(reasons[key.reason || ''] || '暂不可用')} · ${escape(key.cooldownUntil ? new Date(key.cooldownUntil).toLocaleString() : '')} 后可重试` : '可用'}</small></span><small>保留</small></label>`).join('')}${provider?.keys?.length ? '<p class="model-help">取消勾选并保存即可移除。已保存的密钥不回显。</p>' : ''}<div data-new-keys><div class="model-key-input">${field('apiKey', '新增 API 密钥', '', 'type="password" autocomplete="new-password" maxlength="8192" placeholder="无认证的本地接口可留空"')}</div></div><div class="model-key-actions"><button type="button" data-add-key>＋ 添加 Key</button><button type="button" data-reveal>显示密钥</button></div></section><details ${provider?.proxyUrl ? 'open' : ''}><summary>代理设置（可选）</summary>${field('proxyUrl', '代理地址', provider?.proxyUrl, 'type="url" placeholder="http://127.0.0.1:7893"')}</details><label class="model-check"><input name="enabled" type="checkbox" ${provider?.enabled !== false ? 'checked' : ''}>启用连接</label>`
}
export function modelForm(state: AdminModels, model?: CatalogModel, discovered?: { providerId: string; models: string[] }) {
  const c = model?.capabilities
  return `${field('name', '显示名称', model?.name, 'required maxlength="120"')}<label>服务商<select name="providerId" required>${state.providers.map(p => `<option value="${escape(p.id)}" ${(model?.providerId || discovered?.providerId) === p.id ? 'selected' : ''}>${escape(p.name)}</option>`).join('')}</select></label><label>接口协议<select name="adapter">${Object.entries(adapters).map(([key, title]) => `<option value="${key}" ${model?.adapter === key ? 'selected' : ''}>${title}</option>`).join('')}</select></label>${field('model', '上游模型 ID', model?.model, 'required maxlength="120" list="discovered-models"')}<datalist id="discovered-models">${(discovered?.models || []).map(id => `<option value="${escape(id)}"></option>`).join('')}</datalist><p class="model-help">可以直接手填。也可先在服务商连接里获取模型列表；列表不代表生成接口一定兼容。</p><details><summary>计费与排序</summary><div class="model-form-grid">${field('order', '排序（小值在前）', model?.order || 0, 'type="number" min="0" max="10000"')}${field('creditCost', '每次生成点数', model?.creditCost || 0, 'type="number" min="0" max="100000"')}</div><p class="model-help">文本助手暂不计费，请填 0；图片和视频沿用成功扣点、失败释放规则。</p></details><details><summary>模型能力与规格</summary><div class="model-form-grid">${field('referenceImages', '最多参考图', c?.referenceImages || 0, 'type="number" min="0" max="32"')}<label class="model-check" data-image-capability><input name="transparent" type="checkbox" ${c?.transparent ? 'checked' : ''}>支持透明背景</label></div><div data-image-capability>${field('sizes', '图片尺寸（逗号分隔，可留空）', c?.sizes.join(', '), 'placeholder="auto, 1024x1024, 1536x1024"')}</div><div data-video-capability>${field('resolutions', '视频分辨率（逗号分隔）', c?.resolutions.join(', '), 'placeholder="480p, 720p, 1080p"')}${field('aspectRatios', '视频画幅（逗号分隔）', c?.aspectRatios.join(', '), 'placeholder="16:9, 9:16, 1:1"')}<div class="model-form-grid">${field('minSeconds', '最短秒数', c?.minSeconds || 1, 'type="number" min="1" max="600"')}${field('maxSeconds', '最长秒数', c?.maxSeconds || 18, 'type="number" min="1" max="600"')}</div></div><p class="model-help">按接口实际能力填写。留空的规格列表表示不额外限制，仍由上游验证。</p></details><label class="model-check"><input name="enabled" type="checkbox" ${model?.enabled !== false ? 'checked' : ''}>启用模型</label>`
}
export function modelRows(state: AdminModels, query: string, kind: string) {
  const models = state.models.filter(m => (!kind || m.kind === kind) && `${m.name} ${m.model}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.order - b.order || a.name.localeCompare(b.name))
  return models.length ? models.map(m => `<article class="model-row"><div><strong>${escape(m.name)}</strong><small>${escape(m.model)}</small></div><span>${kinds[m.kind]}</span><span>${escape(state.providers.find(p => p.id === m.providerId)?.name || '连接缺失')}</span><span class="model-status">${m.enabled && state.providers.find(p => p.id === m.providerId)?.enabled ? '已启用' : '已停用'}${Object.entries(state.defaults).filter(([, id]) => id === m.id).map(([key]) => `<small>${purposes[key as keyof typeof purposes]}默认</small>`).join('')}</span><button type="button" data-edit-model="${escape(m.id)}">${!state.imported && m.id.startsWith('global:env-') ? '查看' : '编辑'}</button></article>`).join('') : '<p class="model-empty">没有匹配的模型。点击“新增模型”或先导入环境配置。</p>'
}
export function providerRows(state: AdminModels, query = '') {
  const providers = state.providers.filter(p => `${p.name} ${p.baseUrl}`.toLowerCase().includes(query.toLowerCase()))
  return providers.length ? providers.map(p => { const cooling = p.keys?.filter(key => key.status === 'cooling').length || 0; const count = p.keyCount ?? (p.hasKey ? 1 : 0); return `<article class="model-provider-row"><div><strong>${escape(p.name)}</strong><small>${escape(p.baseUrl)}</small><small>${p.enabled ? '已启用' : '已停用'} · ${count} Key${count ? ` · ${count - cooling} 可用` : ''}${cooling ? ` · ${cooling} 冷却中` : ''}${p.readOnly ? ' · 环境配置（只读）' : ''}</small></div><div><button type="button" data-discover="${escape(p.id)}">获取模型</button><button type="button" data-edit-provider="${escape(p.id)}">${p.readOnly ? '查看' : '配置'}</button></div></article>` }).join('') : '<p class="model-empty">没有匹配的服务商，可添加连接或调整搜索。</p>'
}
export function defaultsForm(state: AdminModels) {
  return `<form data-defaults><p>保存后新请求生效，已提交任务不会更换模型。</p>${Object.entries(purposes).map(([purpose, label]) => `<label>${label}<select name="${purpose}"><option value="">不指定默认（新请求须手动选模型）</option>${state.models.filter(m => m.kind === (purpose === 'image' || purpose === 'video' ? purpose : 'text') && m.enabled && state.providers.find(p => p.id === m.providerId)?.enabled).map(m => `<option value="${escape(m.id)}" ${state.defaults[purpose as keyof typeof purposes] === m.id ? 'selected' : ''}>${escape(m.name)}</option>`).join('')}</select></label>`).join('')}<button class="model-primary" type="submit">保存默认分配</button></form>`
}
